### ISSUE TITLE
Overlay disappears when using "restart song"

### ISSUE THREAD

**Issue by LocalH** [LeviSnoot/FNFest-Status#3]
When using "restart song" in Festival, the overlay will disappear until you complete a song and the game loads another. It appears to properly set song_state true but then immediately sets it false. I plan to look at it in more depth tomorrow.

**Comment by LeviSnoot** [comment]
Will investigate. This sounds like it's related to the logic that causes the altering of `song_state` to be delayed by 2 seconds. https://github.com/LeviSnoot/FNFest-Status/blob/c989e1726c2befccba0691bdfec238c8b8afab2e/playerStatus.py#L97-L159

This was kind of a dirty solution to preventing elements from disappearing (or not being ready) before the web app has had time to fade in/out, and we can probably just move that logic to `web/static/js/script.js` instead.

**Comment by LeviSnoot** [comment]
I have looked into this for the past few hours and unfortunately I cannot think of or find a reliable way to detect a song restart. The log outputs have nothing unique about a song restart that I can use to detect it, and my own attempts at adding a "restart flag" when the same song is detected have failed. I'm sure there are ways to achieve this, but at least for now, I can't get it to work.

**Comment by LocalH** [comment]
I have been studying the logs too, and I think I may have a reliable method. Anytime a song stops for any reason, it outputs a line stating "Playback stopped. Last play position" with what appears to be a second-based timestamp. When a song actually plays through to completion, it appears to output a line stating "Playback reached end at play position" with the same timestamp. So perhaps we can track whether we've seen the "reached end" message and if we have not, but we see the "stopped" message, we can presume the user restarted and ignore it? I'm guessing this log event fires when the song audio itself ends, so we wouldn't want to use that state directly to determine when to change visibility, but we could gate the existing end_song_state call behind the state we determine from these playback messages. I won't have time to look into implementing anything for a day or two but it seems feasible.

**Comment by LeviSnoot** [comment]
Thank you! Added a comment to your PR, as soon as that's taken care of we can merge and close!

**Comment by LeviSnoot** [comment]
Closed via #12
